production:
  adapter: sqlite3
  dbfile: db/prod.db
development:
  adapter: sqlite3
  dbfile: db/dev.db
test:
  adapter: sqlite3
  dbfile: db/test.db

# Sample Sqlite 2 Config
#production:
#  adapter: sqlite
#  dbfile: db/prod.db
#development:
#  adapter: sqlite
#  dbfile: db/dev.db
#test:
#  adapter: sqlite
#  dbfile: db/test.db

# Sample Postgresql Config
#production:
#  adapter: postgresql
#  host: localhost
#  database: instiki_prod
#  username: user
#  password: pass
#
#development:
#  adapter: postgresql
#  host: localhost
#  database: instiki_dev
#  username: user
#  password: pass
#
#test:
#  adapter: postgresql
#  host: localhost
#  database: instiki_test
#  username: user
#  password: pass

# Sample MySQL Config
#production:
#  adapter: mysql
#  host: localhost
#  database: instiki_prod
#  username: user
#  password: pass
#
#development:
#  adapter: mysql
#  host: localhost
#  database: instiki_dev
#  username: user
#  password: pass
#
#test:
#  adapter: mysql
#  host: localhost
#  database: instiki_test
#  username: user
#  password: pass

